version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - nbayramberdiyev
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - nbayramberdiyev
